name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CodingJournal.API      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./CodingJournal.API.sln
    - name: Build
      run: dotnet build ./CodingJournal.API.csproj --no-restore
    - name: Test
      run: dotnet test  --no-build --verbosity normal
